In [3]:
import open3d as o3d
import numpy as np 

In [4]:
print("load a ply point cloud, print it, and render it")
pcd=o3d.io.read_point_cloud("cloud/{Enter the file name}.ply")
print(pcd)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd])

load a ply point cloud, print it, and render it
PointCloud with 251266 points.
[[ -9901.352539 -13590.091797  67950.460938]
 [ -9086.081055 -12720.512695  63602.5625  ]
 [ -8741.75293  -12488.21875   62441.089844]
 ...
 [ 51999.246094 116629.226562  57412.417969]
 [ 52176.160156 116658.023438  57426.59375 ]
 [ 52532.671875 117086.929688  57637.726562]]
